services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    networks: 
      - inception_network
    volumes: 
      - mariadb_data:/var/lib/mysql
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    secrets:
      - db_password
      - db_root_password
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart:  always
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    secrets:
      - db_password
      - wp_admin_password
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yblanco-/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yblanco-/data/wordpress
networks:
  inception_network:
    driver: bridge
secrets:
  db_password:
    file: ./requirements/secrets/db_password.txt
  db_root_password:
    file: ./requirements/secrets/db_root_password.txt
  wp_admin_password:
    file: ./requirements/secrets/wp_admin_password.txt
